version: "3.8"
services: 
    api:
        build: ./api
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
            - /app/node_modules
        env_file: env
    db:
        image: postgres
        restart: always
        environtment:
            POSTGRES_PASSWORD: POSTGRES_PASSWORD
        volume:
            - pg_data:/var/lib/postgresql/pg_data
    ui: 
        build: 
            context: ./frontend
            target: build
        ports:
            "5000:8000"
        restart: always
        volumes:
            - ./ui:/app
            - /app/node_modules
volumes:
    pg_data
