version: "3.8"
services: 
    api:
        build: ./api
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
            - /app/node_modules
        env_file: .env
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
    ui: 
        build: 
            context: ./frontend
            target: build
        ports:
            - "7000:8080"
        restart: always
        volumes:
            - ./frontend:/app
            - /app/node_modules
volumes:
    pg_data:
